play.http.secret.key = "changeme-QCYtAnfkaZiwrNwnxIlR6CTfG3gf90Latabg5241ABR5W1uDFNIkn"
play.server.http.port = 9000
play.server.http.address = "0.0.0.0"

play.filters.enabled = []
play.filters.hosts {
  allowed = ["."]
}
